{alpha: 0.4, ann_root: annotation, batch_size_test: 64, batch_size_train: 8, dataset: coco,
image_root: /dataset01/MSCOCO/, image_size: 336, init_lr: 1e-05, max_epoch: 6, min_lr: 0,
pretrained: pretrained/clip_large_retrieval_coco.pth, queue_size: 57600, weight_decay: 0.2}
